import type {
  AgendaEvent,
  CheckIn,
  Course,
  Habit,
  InboxNote,
  Lead,
  Profile,
  Project,
  StudyNote,
  Task,
} from "./types";

function dayOffset(days: number) {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

function sundayIso() {
  const d = new Date();
  const add = d.getDay() === 0 ? 0 : 7 - d.getDay();
  return dayOffset(add);
}

export const seedProfile: Profile = {
  name: "Gabriela",
  role: "Estudante em transição de carreira",
  weeklyFocus:
    "De manhã, leitura e videoaula. À tarde, exercícios e prática de código. LinkedIn só no lote.",
};

export const seedTasks: Task[] = [
  {
    id: "t1",
    title: "Entregar o POS da disciplina de Produtividade",
    notes: "Parte teórica, sistema funcionando, roteiro do pitch e prints.",
    status: "fazendo",
    quadrant: "urgente-importante",
    area: "estudos",
    energy: "alta",
    estimateMin: 90,
    due: dayOffset(2),
    createdAt: dayOffset(-5),
    completedAt: null,
    pomodoros: 3,
  },
  {
    id: "t2",
    title: "Gravar vídeo pitch de até 4 minutos",
    notes: "Contar a saída do Cartório e o sistema da transição.",
    status: "inbox",
    quadrant: "urgente-importante",
    area: "estudos",
    energy: "media",
    estimateMin: 50,
    due: dayOffset(4),
    createdAt: dayOffset(-2),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t3",
    title: "Módulo JS da Rocketseat: funções e arrays",
    notes: "Dois Pomodoros de prática. Não só assistir: code along no editor.",
    status: "inbox",
    quadrant: "importante",
    area: "estudos",
    energy: "alta",
    estimateMin: 50,
    due: dayOffset(1),
    createdAt: dayOffset(-1),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t4",
    title: "Publicar o Norte OS no GitHub com README",
    notes: "Primeiro projeto visível do portfólio da transição.",
    status: "inbox",
    quadrant: "importante",
    area: "portfolio",
    energy: "media",
    estimateMin: 40,
    due: dayOffset(5),
    createdAt: dayOffset(-3),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t5",
    title: "Follow-up da proposta de landing page",
    notes: "Mensagem curta. Sem reabrir o projeto mentalmente o dia inteiro.",
    status: "espera",
    quadrant: "urgente",
    area: "linkedin",
    energy: "baixa",
    estimateMin: 15,
    due: dayOffset(0),
    createdAt: dayOffset(-4),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t6",
    title: "Candidatar-se à vaga de assistente de automação",
    notes: "Só no bloco de lote. Não misturar com o Pomodoro de código.",
    status: "inbox",
    quadrant: "importante",
    area: "linkedin",
    energy: "media",
    estimateMin: 35,
    due: dayOffset(3),
    createdAt: dayOffset(-1),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t7",
    title: "Rolagem no LinkedIn sem critério",
    notes: "Quadrante 4. Substitui a revisão semanal e o lote.",
    status: "inbox",
    quadrant: "nenhum",
    area: "linkedin",
    energy: "baixa",
    estimateMin: 20,
    due: null,
    createdAt: dayOffset(-6),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t8",
    title: "Caminhada de 25 minutos",
    notes: "Contrapeso da rotina de tela. Cartório tinha deslocamento; agora preciso criar o movimento.",
    status: "inbox",
    quadrant: "importante",
    area: "pessoal",
    energy: "baixa",
    estimateMin: 25,
    due: dayOffset(0),
    createdAt: dayOffset(-7),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t9",
    title: "Resumir aula UniFECAF com a IA e guardar em Cursos",
    notes: "Uma página de notas > reler a aula inteira.",
    status: "inbox",
    quadrant: "importante",
    area: "estudos",
    energy: "baixa",
    estimateMin: 20,
    due: dayOffset(1),
    createdAt: dayOffset(-2),
    completedAt: null,
    pomodoros: 0,
  },
  {
    id: "t10",
    title: "Exercício prático: lista de tarefas em JavaScript",
    notes: "Feito no editor, não só no playground da aula.",
    status: "feito",
    quadrant: "importante",
    area: "estudos",
    energy: "alta",
    estimateMin: 45,
    due: dayOffset(-2),
    createdAt: dayOffset(-6),
    completedAt: dayOffset(-2),
    pomodoros: 2,
  },
  {
    id: "t11",
    title: "Ler Trello Guide e espelhar o quadro no POS",
    notes: "Kanban das frentes da transição.",
    status: "feito",
    quadrant: "importante",
    area: "estudos",
    energy: "media",
    estimateMin: 30,
    due: dayOffset(-3),
    createdAt: dayOffset(-8),
    completedAt: dayOffset(-3),
    pomodoros: 1,
  },
];

export const seedEvents: AgendaEvent[] = [
  {
    id: "e1",
    title: "Leitura e videoaula — faculdade",
    date: dayOffset(0),
    start: "09:00",
    end: "11:00",
    kind: "aula",
    notes: "Manhã: leitura e videoaula. Celular fora.",
  },
  {
    id: "e2",
    title: "Pausa e caminhada",
    date: dayOffset(0),
    start: "12:30",
    end: "13:00",
    kind: "exercicios",
    notes: "Longe da tela.",
  },
  {
    id: "e3",
    title: "Exercícios e prática de código",
    date: dayOffset(0),
    start: "14:00",
    end: "15:30",
    kind: "codigo",
    notes: "Tarde: exercícios e prática de código. Não só assistir.",
  },
  {
    id: "e4",
    title: "Lote: vagas, follow-up e mensagens",
    date: dayOffset(0),
    start: "17:00",
    end: "17:40",
    kind: "lote",
    notes: "Único horário em que LinkedIn é permitido.",
  },
  {
    id: "e5",
    title: "Leitura — Rocketseat (cursos)",
    date: dayOffset(1),
    start: "09:00",
    end: "10:30",
    kind: "estudo",
    notes: "Manhã para leitura. A prática de código fica para a tarde.",
  },
  {
    id: "e6",
    title: "Revisão semanal (ritual de fechamento)",
    date: sundayIso(),
    start: "10:00",
    end: "11:00",
    kind: "compromisso",
    notes: "Domingo: o que avançou em cada frente. Sem candidatar no mesmo bloco.",
  },
];

export const seedHabits: Habit[] = [
  {
    id: "h1",
    name: "Dormir até 23h30",
    detail: "",
    targetPerWeek: 6,
    logs: [],
  },
  {
    id: "h2",
    name: "Pausa sem tela",
    detail: "",
    targetPerWeek: 5,
    logs: [],
  },
  {
    id: "h3",
    name: "Caminhada ou alongamento",
    detail: "",
    targetPerWeek: 4,
    logs: [],
  },
  {
    id: "h4",
    name: "Um minuto em silêncio antes de estudar",
    detail: "",
    targetPerWeek: 5,
    logs: [],
  },
];

export const seedCheckins: CheckIn[] = [
  {
    date: dayOffset(-3),
    mood: 2,
    energy: 3,
    note: "Abri o LinkedIn no meio da aula. Saí pior do que entrei.",
  },
  {
    date: dayOffset(-2),
    mood: 4,
    energy: 4,
    note: "Leitura e videoaula de manhã. À tarde, a prática de código rendeu.",
  },
  {
    date: dayOffset(-1),
    mood: 4,
    energy: 3,
    note: "Saudade da rotina rígida do Cartório — o POS segura o dia.",
  },
];

export const seedInbox: InboxNote[] = [
  {
    id: "n1",
    text: "Ideia de projeto: calculadora de emolumentos / checklist de registro — usar o conhecimento do Cartório no portfólio.",
    createdAt: dayOffset(-2),
  },
  {
    id: "n2",
    text: "Edital de vaga júnior em automação de planilhas. Avaliar no lote, não agora.",
    createdAt: dayOffset(0),
  },
];

export const seedCourses: Course[] = [
  {
    id: "c1",
    name: "Produtividade e Gestão do Tempo",
    provider: "UniFECAF (faculdade)",
    modules: 8,
    done: 4,
    current: "GTD, Eisenhower e Segundo cérebro",
    syllabus: [
      "Parkinson e Pareto",
      "Matriz de Eisenhower",
      "GTD",
      "Segundo cérebro",
      "GTD, Eisenhower e Segundo cérebro",
      "Método PARA",
      "Time blocking",
      "Sistema operacional pessoal",
    ],
    outcome: "Entregar o POS da disciplina e gravar o pitch de 4 minutos.",
    deadline: dayOffset(10),
    distill:
      "Curso que vira o sistema: GTD para capturar, Eisenhower para decidir, PARA para guardar. O entregável é o Norte OS, não só a prova.",
    packets: [
      { id: "c1p1", title: "Notas destiladas de cada aula", done: true },
      { id: "c1p2", title: "POS funcionando com PARA e Foco", done: true },
      { id: "c1p3", title: "Roteiro do vídeo-pitch", done: false },
      { id: "c1p4", title: "Prints e link no GitHub", done: false },
    ],
  },
  {
    id: "c2",
    name: "Formação em programação",
    provider: "Rocketseat (cursos)",
    modules: 12,
    done: 3,
    current: "JavaScript: funções, map e filter",
    syllabus: [
      "Fundamentos da web",
      "HTML e CSS",
      "JavaScript: variáveis e tipos",
      "JavaScript: funções, map e filter",
      "DOM e eventos",
      "Git e GitHub",
      "Lógica e algoritmos",
      "HTTP e APIs",
      "React: componentes",
      "React: estado",
      "Projeto prático",
      "Portfólio e deploy",
    ],
    outcome: "Publicar um projeto no GitHub que use JS de verdade, não só aula assistida.",
    deadline: null,
    distill:
      "Prática antes de teoria extra. Cada módulo vira um pacote pequeno: função, lista, página. Assistir sem digitar não conta.",
    packets: [
      { id: "c2p1", title: "Lista de tarefas em JavaScript", done: true },
      { id: "c2p2", title: "Exercício de map/filter no editor", done: false },
      { id: "c2p3", title: "Página com HTML/CSS no GitHub", done: false },
    ],
  },
];

export const seedProjects: Project[] = [
  {
    id: "p1",
    name: "Norte OS (POS da disciplina)",
    stack: "TypeScript, React",
    status: "progresso",
    next: "Fechar a parte prática e o roteiro do vídeo.",
    outcome: "POS publicado, com README, prints e roteiro do pitch.",
    deadline: dayOffset(7),
    distill:
      "O artefato da transição: GTD, PARA e Foco num app que eu mesma uso. Expressar = GitHub + vídeo, não só anotar.",
    packets: [
      { id: "p1k1", title: "README com o propósito da transição", done: true },
      { id: "p1k2", title: "Prints das telas PARA e Foco", done: false },
      { id: "p1k3", title: "Roteiro do vídeo de 4 min", done: false },
    ],
  },
  {
    id: "p2",
    name: "Calculadora de emolumentos",
    stack: "HTML, CSS, JavaScript",
    status: "ideia",
    next: "Definir o primeiro commit com a tabela de emolumentos.",
    outcome: "Página que calcula emolumentos a partir da tabela, no GitHub.",
    deadline: null,
    distill:
      "Usa o conhecimento do Cartório. Pacote intermediário: a tabela; depois o cálculo; depois o visual.",
    packets: [
      { id: "p2k1", title: "Tabela de emolumentos em JSON", done: false },
      { id: "p2k2", title: "Função de cálculo", done: false },
      { id: "p2k3", title: "Página simples no ar", done: false },
    ],
  },
  {
    id: "p3",
    name: "AppBooks",
    stack: "JavaScript",
    status: "ideia",
    next: "Listar o MVP: cadastro de livro e busca.",
    outcome: "Cadastro e busca de livros no navegador.",
    deadline: null,
    distill: "MVP mínimo: um livro entra, um livro aparece na busca. Sem login.",
    packets: [
      { id: "p3k1", title: "Lista do MVP em 5 linhas", done: false },
      { id: "p3k2", title: "Cadastro de livro", done: false },
      { id: "p3k3", title: "Busca por título", done: false },
    ],
  },
  {
    id: "p4",
    name: "Storytelling de peças",
    stack: "HTML, CSS",
    status: "publicado",
    next: "Link no README e uma captura no portfólio.",
    outcome: "Página no GitHub contando a história das peças.",
    deadline: dayOffset(-20),
    distill: "Já expresso. Arquivar depois de colocar o link no portfólio.",
    packets: [
      { id: "p4k1", title: "Página HTML/CSS", done: true },
      { id: "p4k2", title: "Publicar no GitHub", done: true },
      { id: "p4k3", title: "Link no README do Norte OS", done: false },
    ],
  },
];

export const seedLeads: Lead[] = [
  {
    id: "l1",
    title: "Landing page para estúdio local",
    company: "Cliente freelancer",
    kind: "freela",
    status: "prospectar",
    nextAction: "Mandar mensagem curta de acompanhamento.",
    followUp: dayOffset(0),
  },
  {
    id: "l2",
    title: "Assistente de automação / planilhas",
    company: "Escritório em SC",
    kind: "vaga",
    status: "prospectar",
    nextAction: "Adaptar currículo com a transição Cartório → automação.",
    followUp: dayOffset(3),
  },
  {
    id: "l3",
    title: "Estágio em suporte técnico",
    company: "Empresa de software",
    kind: "vaga",
    status: "enviado",
    nextAction: "Anotar o feedback e voltar ao código.",
    followUp: null,
  },
  {
    id: "l4",
    title: "Júnior backend",
    company: "Wave",
    kind: "vaga",
    status: "followup",
    nextAction: "Preparar mensagem no bloco de lote.",
    followUp: dayOffset(1),
  },
  {
    id: "l5",
    title: "Dashboard a partir de planilha",
    company: "Pequeno comércio",
    kind: "freela",
    status: "enviado",
    nextAction: "Esperar retorno até sexta; então follow-up.",
    followUp: dayOffset(2),
  },
];

export const seedNotes: StudyNote[] = [
  {
    id: "sn1",
    area: "estudos",
    title: "GTD em uma frase",
    body: "Capturar tudo fora da cabeça. UniFECAF, Rocketseat, ideias de projeto e editais não podem viver só no WhatsApp.",
    para: "recursos",
    createdAt: dayOffset(-3),
    tags: ["estudos", "unifecaf-faculdade", "ia"],
    projectId: null,
    courseId: "c1",
  },
  {
    id: "sn2",
    area: "estudos",
    title: "Função é bloco reutilizável",
    body: "Pratiquei map/filter numa lista de tarefas. Assistir a aula sem digitar não conta como módulo feito.",
    para: "recursos",
    createdAt: dayOffset(-2),
    tags: ["estudos", "rocketseat-cursos", "programacao"],
    projectId: null,
    courseId: "c2",
  },
];
