/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppComunicacaoRouteImport } from './routes/_app/comunicacao'
import { Route as AppFocoRouteImport } from './routes/_app/foco'
import { Route as AppFrentesRouteImport } from './routes/_app/frentes'
import { Route as AppIaRouteImport } from './routes/_app/ia'
import { Route as AppTarefasRouteImport } from './routes/_app/tarefas'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacaoRoute = AppComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => AppRoute,
} as any)
const AppFocoRoute = AppFocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => AppRoute,
} as any)
const AppFrentesRoute = AppFrentesRouteImport.update({
  id: '/frentes',
  path: '/frentes',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agenda': typeof AppAgendaRoute
  '/comunicacao': typeof AppComunicacaoRoute
  '/foco': typeof AppFocoRoute
  '/frentes': typeof AppFrentesRoute
  '/ia': typeof AppIaRoute
  '/tarefas': typeof AppTarefasRoute
}
export interface FileRoutesByTo {
  '/agenda': typeof AppAgendaRoute
  '/comunicacao': typeof AppComunicacaoRoute
  '/foco': typeof AppFocoRoute
  '/frentes': typeof AppFrentesRoute
  '/ia': typeof AppIaRoute
  '/tarefas': typeof AppTarefasRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/comunicacao': typeof AppComunicacaoRoute
  '/_app/foco': typeof AppFocoRoute
  '/_app/frentes': typeof AppFrentesRoute
  '/_app/ia': typeof AppIaRoute
  '/_app/tarefas': typeof AppTarefasRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/agenda' | '/comunicacao' | '/foco' | '/frentes' | '/ia' | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/agenda' | '/comunicacao' | '/foco' | '/frentes' | '/ia' | '/tarefas' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agenda'
    | '/_app/comunicacao'
    | '/_app/foco'
    | '/_app/frentes'
    | '/_app/ia'
    | '/_app/tarefas'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunicacao': {
      id: '/_app/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof AppComunicacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foco': {
      id: '/_app/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof AppFocoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frentes': {
      id: '/_app/frentes'
      path: '/frentes'
      fullPath: '/frentes'
      preLoaderRoute: typeof AppFrentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas': {
      id: '/_app/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppComunicacaoRoute: typeof AppComunicacaoRoute
  AppFocoRoute: typeof AppFocoRoute
  AppFrentesRoute: typeof AppFrentesRoute
  AppIaRoute: typeof AppIaRoute
  AppTarefasRoute: typeof AppTarefasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppComunicacaoRoute: AppComunicacaoRoute,
  AppFocoRoute: AppFocoRoute,
  AppFrentesRoute: AppFrentesRoute,
  AppIaRoute: AppIaRoute,
  AppTarefasRoute: AppTarefasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
